# Generated by Django 4.2.8 on 2024-05-22 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('interest_type', models.CharField(max_length=20)),
                ('save_term', models.CharField(max_length=3)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('max_interest_rate', models.FloatField(blank=True, null=True)),
                ('product_type', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
