# Generated by Django 4.2.8 on 2024-05-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialproduct',
            name='dcls_end_day',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='dcls_month',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='dcls_strt_day',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='fin_co_subm_day',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='join_deny',
        ),
        migrations.RemoveField(
            model_name='financialproduct',
            name='max_limit',
        ),
        migrations.RemoveField(
            model_name='optionlist',
            name='fin_co_no',
        ),
    ]
