# Generated by Django 4.2.8 on 2024-05-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_remove_financialproduct_dcls_end_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionlist',
            name='dcls_month',
        ),
    ]
