# Generated by Django 4.2.8 on 2024-05-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_depositproduct_depositoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositproduct',
            name='dcls_end_day',
        ),
        migrations.RemoveField(
            model_name='depositproduct',
            name='dcls_strt_day',
        ),
        migrations.RemoveField(
            model_name='depositproduct',
            name='fin_co_subm_day',
        ),
        migrations.RemoveField(
            model_name='depositproduct',
            name='max_limit',
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionlist',
            name='intr_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionlist',
            name='intr_rate2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
