# Generated by Django 4.2.8 on 2024-05-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_remove_depositproduct_dcls_month_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositOption',
        ),
        migrations.DeleteModel(
            name='DepositProduct',
        ),
    ]
