# Generated by Django 4.2.8 on 2024-05-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepositOption',
            new_name='OptionList',
        ),
    ]
