# Generated by Django 4.2.8 on 2024-05-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_nm', models.CharField(max_length=100)),
                ('cur_unit', models.CharField(max_length=10)),
                ('deal_bas_r', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ttb', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
